MySQL:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password: 292378
  Database: go_shop
  Config: charset=utf8mb4&parseTime=True&loc=Local
App:
  Port: 8090
Jwt:
  Issuer: 牧牛火链
  ExpireTime: 600
  Secret: 牧牛火链
Redis:
  Host: 127.0.0.1
  Port: 6379
  Password: ""
  DB: 0
Logger:
  Level: info
  Direcotr: logs
  Layout: 2006-01-02 15-04
Kafka:
  Host: 127.0.0.1
  Port: 9092